version: '2.3'
services:
  finder:
    build: ./applications/finder
    image: eduardomioto/finder
    container_name: finder
    restart: always
    ports:
     - 19100:19100
    links:
     - "consul"
     - "mysql"
     - "neo4j"
    depends_on:
     - "consul"
     - "neo4j"
     - "mysql"
    environment:
     - "SPRING_PROFILES_ACTIVE=dev"
  visualizer:
    build:
      context: ./applications/visualizer
    image: eduardomioto/visualizer
    container_name: visualizer
    restart: on-failure
    ports:
      - 7000:80
    links:
      - "consul"
      - "mysql"
      - "finder"
      - "specialist_opinion"      
    depends_on:
      - "finder"
      - "specialist_opinion"
    environment:
      - "NGINX_PORT=80"
    volumes:  
      - ./volumes/visualizer/:/usr/share/nginx/html
  specialist_opinion:
    build:
     context: ./applications/specialist-opinion
    image: eduardomioto/specialist-opinion
    container_name: specialist_opinion
    restart: on-failure
    ports:
      - 19192:19192
    links:
      - "consul"
      - "mysql"
    depends_on:
      - "consul"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  architecture_probe:
    build: 
      context: ./applications/architecture-probe
    image: eduardomioto/architecture-probe
    container_name: architecture_probe
    restart: on-failure
    ports:
      - 19099:19099
    links:
      - "consul"
      - "sonarqube"
      - "mysql"
    environment:
      - docker-stats=host.docker.internal
  #
  #
  #
  #
  #
  #
  #
  #
  #    
  consul:
    image: "progrium/consul"
    restart: always
    container_name: consul
    hostname: "consul"
    volumes:
      - ./volumes/consul/data:/volumes/data/consul
      - ./volumes/consul/config:/volumes/config/consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "-server -bootstrap -ui-dir /ui -join=127.0.0.1 "
  neo4j:
    image: library/neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/neo4j/:/data/dbms
  sonarqube:
    build:
      context: ./applications/sonar
    restart: unless-stopped
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ./volumes/sonarqube/conf:/opt/sonarqube/conf
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
  postgres:
    image: postgres:10.1
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      -  ./volumes/postgres/:/var/lib/postgresql/data
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'm2csea-metrics'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      -  ./volumes/mysql/:/var/lib/mysql
  #
  #
  #
  #
  #
  #
  #
  access_manager:
    build: 
      context: ./applications/simulated/java/microservice-access-manager-rest
    image: eduardomioto/rest-access-manager
    container_name: access_manager
    restart: on-failure
    mem_limit: 1000MB
    ports:
      - "10001:10001"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - "consul"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
  fare:
    build:
      context: ./applications/simulated/java/microservice-fare-rest
    image: eduardomioto/rest-fare
    restart: on-failure
    mem_limit: 1000MB
    container_name: fare
    ports:
      - "10008:10008"
    links:
      - "consul"
      - "mysql"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
  order:
    build: 
      context: ./applications/simulated/java/microservice-order-rest
    image: eduardomioto/rest-order
    restart: on-failure
    mem_limit: 1000MB
    container_name: order
    ports:
      - "10012:10012"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - "consul"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
  product:
    build: 
      context: ./applications/simulated/java/microservice-product-rest
    image: eduardomioto/rest-product
    restart: on-failure
    mem_limit: 1000MB
    container_name: product
    ports:
      - "10015:10015"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - "consul"
      - "fare"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
  user_manager:
    build: 
      context: ./applications/simulated/java/microservice-user-manager-rest
    image: eduardomioto/rest-user-manager
    restart: on-failure
    mem_limit: 1000MB
    container_name: user_manager
    ports:
      - "10017:10017"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - "consul"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
  newsletter:
    build: 
      context: ./applications/simulated/node/microservice-newsletter-rest
    image: eduardomioto/rest-newsletter
    restart: on-failure
    mem_limit: 1000MB
    container_name: newsletter
    ports:
      - "10011:10011"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - consul
    environment:
      - CONSUL_URL=consul
  banner:
    build: 
      context: ./applications/simulated/node/microservice-banner-rest
    image: eduardomioto/rest-banner
    restart: always
    mem_limit: 1000MB
    container_name: banner
    ports:
      - "10002:10002"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - consul
    environment:
      - CONSUL_URL=consul
  calendar:
    build: 
      context: ./applications/simulated/node/microservice-calendar-rest
    image: eduardomioto/rest-calendar
    restart: always
    mem_limit: 1000MB
    container_name: calendar
    ports:
      - "10006:10006"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - consul
    environment:
      - CONSUL_URL=consul
  category:
    build: 
      context: ./applications/simulated/node/microservice-category-rest
    image: eduardomioto/rest-category
    restart: always
    mem_limit: 1000MB
    container_name: category
    ports:
      - "10007:10007"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - consul
    environment:
      - CONSUL_URL=consul
  benefits:
    build: 
      context: ./applications/simulated/node/microservice-benefits-rest
    image: eduardomioto/rest-benefits
    restart: on-failure
    mem_limit: 1000MB
    container_name: benefits
    ports:
      - "10004:10004"
    links:
      - "consul"
      - "mysql"
    depends_on:
      - consul
    environment:
      - CONSUL_URL=consul
networks:
  default:
    external:
      name: m2csea