version: '2.1'
services:
#
# Consul > Service Discovery and Repository
#
 consul1:
  image: "progrium/consul"
  restart: always
  container_name: "consul1"
  hostname: "consul1"
  volumes:
   - ./volumes/consul/data:/volumes/data/consul
   - ./volumes/consul/config:/volumes/config/consul
  ports:
   - "8300:8300"
   - "8400:8400"
   - "8500:8500"
   - "8600:8600"
  command: "-server -bootstrap -ui-dir /ui -join=127.0.0.1 "
#
# Neo4J > Graph Database
#
 neo4j:
  image: library/neo4j
  ports:
   - "7474:7474"
   - "7687:7687"
  volumes:
   - /volumes/neo4j/:/data/dbms
#
# ZipKin > Open Tracing
#
 zipkin:
  image: "openzipkin/zipkin"
  ports:
   - "9411:9411"
 zipkin-ui:
  image: openzipkin/zipkin-ui
  environment:
    - ZIPKIN_BASE_URL=http://zipkin:9411
  ports:
    - 80:80
  depends_on:
    - zipkin
#
# MySQL > Relational Database
#
 mysql:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=admin
   - MYSQL_DATABASE=mc2pd
  ports:
   - "3306:3306"
  volumes:
   - /volumes/mysql/:/var/lib/mysql
#
# KeyCloak > Authentication and Authorization
#
# keycloak:
#  context: ./keycloak
#  container_name: keycloak
#  environment:
#    - KEYCLOAK_USER: admin
#    - KEYCLOAK_PASSWORD: admin
#  ports:
#    - 8282:8080
#    - 8383:8443
#  volumes:
#    - ./volumes/keycloak:/opt/jboss/keycloak/standalone/data