version: '2.1'
services:
#
# Consul > Service Discovery and Repository
#
 consul1:
  image: "progrium/consul"
  restart: always
  container_name: "consul1"
  hostname: "consul1"
  volumes:
   - ./volumes/consul/data:/volumes/data/consul
   - ./volumes/consul/config:/volumes/config/consul
  ports:
   - "8300:8300"
   - "8400:8400"
   - "8500:8500"
   - "8600:8600"
  command: "-server -bootstrap -ui-dir /ui -join=127.0.0.1 "
#
# Neo4J > Graph Database
#
 neo4j:
  image: library/neo4j
  ports:
   - "7474:7474"
   - "7687:7687"
  volumes:
   - /volumes/neo4j/:/data/dbms
#
# Zipkin > Open Tracing
#
 zipkin:
  image: "openzipkin/zipkin"
  ports:
   - "9411:9411"
 zipkin-ui:
  image: openzipkin/zipkin-ui
  environment:
    # Change this if connecting to a different zipkin server
    - ZIPKIN_BASE_URL=http://zipkin:9411
  ports:
    - 80:80
  depends_on:
    - zipkin
